### ISSUE TITLE
Kafka-connector consume slower

### ISSUE THREAD

**Issue by mrmassis** [openfaas/kafka-connector#62]
Hi,
im using the kafka-connector to consume from a topic with 1 partition.
My problem is that the consumer is slower. And consume only one and one message.
There is anything to accelerate the process? After 3 hours i have a difference about 40 minutes between production and consume.
Tkz

**Comment by alexellis** [comment]
Hi, there are a couple of things that can be done.

I would suggest that the async behaviour is used, so that the requests come out of Kafka and into our NATS streaming queue. It can execute in massive parallelism if required.

We could also explore having the connector-sdk execute a number of requests in parallel.

Going forward, you really need to use the issue template and if you delete it again we may not answer you. Does that sound fair? https://raw.githubusercontent.com/openfaas/kafka-connector/master/.github/ISSUE_TEMPLATE.md

**Comment by mrmassis** [comment]
Ok, sorry by template fault.
